# Generated by Django 4.2.30 on 2026-05-08 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('world_type', models.CharField(choices=[('modern', '现代都市'), ('ancient', '古代江湖'), ('future', '未来科幻')], max_length=20)),
                ('attributes', models.JSONField(default=dict)),
                ('background', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('current_stage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ending', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
