/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIItinerary: typeof import('./src/components/AIItinerary.vue')['default']
    CoordinateLibrary: typeof import('./src/components/CoordinateLibrary.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ItineraryPanel: typeof import('./src/components/ItineraryPanel.vue')['default']
    LandmarkDock: typeof import('./src/components/LandmarkDock.vue')['default']
    LandmarkList: typeof import('./src/components/LandmarkList.vue')['default']
    LandmarkPopup: typeof import('./src/components/LandmarkPopup.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
  }
}
